version: '3.8'

services:
  # Backend API service
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - PORT=5000
      - MONGODB_URI=mongodb://mongo:27017/work-manager
      - NODE_ENV=development
    depends_on:
      - mongo
    restart: unless-stopped
    networks:
      - app-network

  # MongoDB service
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - app-network
    restart: unless-stopped

# Volumes
volumes:
  mongo-data:
    driver: local

# Networks
networks:
  app-network:
    driver: bridge 