version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19006:19006"  # Web port
      - "19000:19000"  # Native port
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
    environment:
      - NODE_ENV=development
      - REACT_NATIVE_PACKAGER_HOSTNAME=0.0.0.0
      - EXPO_DEVTOOLS_LISTEN_ADDRESS=0.0.0.0
      # Remove backend dependency for demo purposes
      - EXPO_PUBLIC_API_URL=http://localhost:19006

volumes:
  frontend_node_modules: 