version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "19006:19006"  # Web port
    volumes:
      - ./frontend:/app
      - frontend_node_modules:/app/node_modules
      # Store the web-build directory for persistence
      - frontend_web_build:/app/web-build
    environment:
      - NODE_ENV=development
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:19006"]
      interval: 5s
      timeout: 3s
      retries: 5

volumes:
  frontend_node_modules:
  frontend_web_build: 